# Generated by Django 4.0.5 on 2022-07-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('client', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idItem', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('volume', models.IntegerField()),
                ('dimensao', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=5)),
                ('ambiente', models.CharField(max_length=30)),
                ('largura', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('modelo', models.CharField(max_length=30)),
                ('colecao', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=30)),
                ('acion', models.CharField(max_length=30)),
                ('quant', models.CharField(max_length=30)),
                ('tubo', models.CharField(max_length=30)),
                ('perfil', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('pos', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
    ]
