# Generated by Django 4.0.5 on 2022-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_client_alter_order_id_pipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ambiente',
            field=models.CharField(default='', max_length=30),
        ),
    ]
